- name: Dotfiles -> pull
  git: repo=git@github.com:kyrieleison/dotfiles.git dest=/root/.dotfiles accept_hostkey=yes update=yes version=master
  poll: 30

- name: Build dotfiles
  shell: ./build.sh
  args:
    chdir: ~/.dotfiles

- name: Build dotfiles
  shell: ./deploy.sh
  args:
    chdir: ~/.dotfiles

- name: Change shell
  shell: chsh -s $(grep /zsh$ /etc/shells | tail -1)
