- name: Yum install -> ruby basic package
  yum: name={{ item }} state=latest
  with_items:
    - gnupg2

- name: Install rvm
  shell: curl -sSL https://get.rvm.io | bash

- name: Check ruby version
  command: /bin/bash -l -c "which ruby"
  register: ruby_version_check
  ignore_errors: yes
  always_run: yes

- name: Install Ruby
  command: /bin/bash -l -c "rvm install {{ ruby_version }} && rvm --default {{ ruby_version }}"
  when: ruby_version_check|changed

